-- ============================================================================
-- PDF Branding Customization for Pro/Scale Users
-- Migration: 041_add_pdf_branding.sql
--
-- Allows users on Pro/Scale plans to customize PDF report output:
-- - Custom primary and accent colors
-- - Custom logo (uploaded to storage)
-- - Hide default "Generated by Romy" footer
-- - Custom footer text
-- ============================================================================

-- PDF Branding table
CREATE TABLE IF NOT EXISTS pdf_branding (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Color settings (hex format)
  primary_color TEXT DEFAULT '#0f172a',
  accent_color TEXT DEFAULT '#00A5E4',

  -- Logo settings
  logo_url TEXT,                    -- Supabase storage URL
  logo_base64 TEXT,                 -- Cached base64 for fast PDF generation
  logo_content_type TEXT,           -- image/png, image/jpeg

  -- Footer settings
  hide_default_footer BOOLEAN DEFAULT false,
  custom_footer_text TEXT,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- One branding config per user
  UNIQUE(user_id)
);

-- Index for fast lookups by user_id
CREATE INDEX IF NOT EXISTS idx_pdf_branding_user_id ON pdf_branding(user_id);

-- Auto-update timestamp trigger
CREATE OR REPLACE FUNCTION update_pdf_branding_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_pdf_branding_timestamp ON pdf_branding;
CREATE TRIGGER update_pdf_branding_timestamp
BEFORE UPDATE ON pdf_branding
FOR EACH ROW
EXECUTE PROCEDURE update_pdf_branding_updated_at();

-- ============================================================================
-- Row Level Security
-- ============================================================================

ALTER TABLE pdf_branding ENABLE ROW LEVEL SECURITY;

-- Users can only view their own branding
DROP POLICY IF EXISTS "Users can view their own pdf branding" ON pdf_branding;
CREATE POLICY "Users can view their own pdf branding"
  ON pdf_branding FOR SELECT
  USING (auth.uid() = user_id);

-- Users can create their own branding
DROP POLICY IF EXISTS "Users can create their own pdf branding" ON pdf_branding;
CREATE POLICY "Users can create their own pdf branding"
  ON pdf_branding FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own branding
DROP POLICY IF EXISTS "Users can update their own pdf branding" ON pdf_branding;
CREATE POLICY "Users can update their own pdf branding"
  ON pdf_branding FOR UPDATE
  USING (auth.uid() = user_id);

-- Users can delete their own branding
DROP POLICY IF EXISTS "Users can delete their own pdf branding" ON pdf_branding;
CREATE POLICY "Users can delete their own pdf branding"
  ON pdf_branding FOR DELETE
  USING (auth.uid() = user_id);

-- ============================================================================
-- Storage Bucket for PDF Branding Logos
-- ============================================================================

-- Create storage bucket for PDF branding logos
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'pdf-branding',
  'pdf-branding',
  true,                                           -- Public access for PDF generation
  2097152,                                        -- 2MB limit
  ARRAY['image/jpeg', 'image/png', 'image/gif']  -- No SVG for security
)
ON CONFLICT (id) DO UPDATE SET
  public = true,
  file_size_limit = 2097152,
  allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/gif'];

-- ============================================================================
-- Storage Policies
-- ============================================================================

-- Users can upload their own branding logos (path must start with their user ID)
DROP POLICY IF EXISTS "Users can upload their own branding logos" ON storage.objects;
CREATE POLICY "Users can upload their own branding logos"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'pdf-branding' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- Users can view their own branding logos
DROP POLICY IF EXISTS "Users can view their own branding logos" ON storage.objects;
CREATE POLICY "Users can view their own branding logos"
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'pdf-branding' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- Users can update their own branding logos
DROP POLICY IF EXISTS "Users can update their own branding logos" ON storage.objects;
CREATE POLICY "Users can update their own branding logos"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'pdf-branding' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- Users can delete their own branding logos
DROP POLICY IF EXISTS "Users can delete their own branding logos" ON storage.objects;
CREATE POLICY "Users can delete their own branding logos"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'pdf-branding' AND
  (storage.foldername(name))[1] = auth.uid()::text
);

-- Public read access for PDF generation (logos need to be accessible)
DROP POLICY IF EXISTS "Public can view branding logos" ON storage.objects;
CREATE POLICY "Public can view branding logos"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'pdf-branding');
